draft_explanation_task:
  description: >
    Write a draft post in the style of 5 Levels (https://www.wired.com/video/series/5-levels) about '{topic}' 
    that is clear, concise, and engaging. The post should be written in a way that is easy to understand 
    for someone who is new to '{topic}'. 

    Each of the 5-levels sections of the post should be limited to no more than 100 words.  Supplemental information can be provided in the appendix with more details.
    
    Specifically, it should be broken down into sections with clear headings and bullet points exaplaining the main topics
    at the following levels:

    - Level 1: Can you explain it to a child?
    - Level 2: Can you explain it to a teenager?
    - Level 3: Can you explain it to an undergrad?
    - Level 4: Can you explain it to a grad student?
    - Level 5: Can you explain it to a college, an expert scientist?

    Next, include any key terms or concepts that are important to understand the topic with definition.

    Finally, include the full text of the research report that was used to write the draft post.

    The document should be in markdown format.

    Leverage the following research material to write the draft post.
    {research_report}

    Please incoporate feedback if present.
    {feedback}

  expected_output: >
    The content that explains the concept of '{topic}' in a clear, concise, and engaging way.
    The content broken down into sections explained at each level.
    The document should be well structured in markdown format, without the ````markdown ``` wrapper.

    At the end of the document, include the full text of the research report that was used to write the draft post.

  agent: writer