research_task:
  description: >
    Conduct a thorough research about {topic} make sure you find any interesting and relevant information given
    the current date is {date}.  Ensure you provide a list of the most relevant information about {topic} 
    as well as any links to the source material. For key terms, be certain to provide a definition and a link 
    to the source material that would explain that term for further investigation.

    Your final response must include:
    - title: A title for the research report
    - findings: A document no more than 5000 words long, providing data points of the most relevant information about {topic} and links to the source material.
    - key_terms: A list of key terms with definitions and links to the source material.

  expected_output: >
    title: A title for the research report
    findings: A document no more than 5000 words long, providing data points of the most relevant information about {topic} and links to the source material.
    key_terms: A list of key terms with definitions and links to the source material.
  agent: researcher
