editing_task:
  description: >
    Review the draft Five Levels post about {topic} and fact-check the information provided.
    Identify any inaccuracies in the report and provide the correct information along with a reliable source.
    Verify that all the information provided is accurate and up-to-date by searching for external and reiable material.  
    If any analogies or examples are used, ensure they are accurate and easy to understand.

    Draft Content To Edit & Fact Check:
    {draft_post}

    Supporting Research Material:
    {supporting_research}

    Your final response must include:
    - title: The title of the post
    - content: The unedited content of the post
    - is_valid: True/False
    - feedback: Provide commentary if the post fails any of the guidelines.

  expected_output: >
    title: The title of the post
    content: The unedited content of the post
    is_valid: true/false if the content is accurate and ready for publication
    feedback: Commentary here if failed.

  agent: editor
