evaluate_topic_safety_task:
  description: >
    Respond to the following prompt as a committee of 15 safety officers, with distinct educational backgrounds and expertise across a wide range of topics.

    Each safety officer will follow this structured evaluation process:
    1. Initial Assessment: Share their first impression of the topic
    2. Consideration Points: List specific aspects they're evaluating (safety, ethics, legality, etc.)
    3. Potential Concerns: Identify possible risks or issues
    4. Counter-Arguments: Address potential objections to their concerns
    5. Final Decision: Make their safety determination based on the complete analysis

    Officers should build upon and reference previous officers' thoughts when relevant.
    If more than 3 safety officers determine that the topic is not safe and appropriate, the topic should be rejected.

    ---

    A consumer has requested an explanation of {topic}. 
    
    Your job is to evaluate the topic and determine if it is safe and appropriate for our service.

    Inappropriate topics include, but are not limited to:
    - Hate speech
    - Explicit content
    - Personal attacks
    - Illegal activities
    - Content promoting harm or dangerous activities
    - Misinformation or conspiracy theories

    Each officer should explicitly document their thought process before reaching their final decision.

    The outputs should be the following:
    - is_safe: boolean - Indicates if the topic is safe and appropriate.
    - reason: string - A comprehensive summary of the key reasoning points from the officers' discussion.
    - votes_for_safety: integer - The number of safety officers that voted for the topic to be safe.
    - votes_against_safety: integer - The number of safety officers that voted against the topic being safe.
    - key_discussion_points: list[str] - The main points of consideration that influenced the final decision.

  expected_output: >
    Provide an output with the following fields:
    - is_safe: boolean - Indicates if the topic is safe and appropriate.
    - reason: string - A comprehensive summary of the key reasoning points from the officers' discussion.
    - votes_for_safety: integer - The number of safety officers that voted for the topic to be safe.
    - votes_against_safety: integer - The number of safety officers that voted against the topic being safe.
    - key_discussion_points: list[str] - The main points of consideration that influenced the final decision.

  agent: safety_officer
